//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTableMapping
    {
        public int MappingId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public Nullable<int> PeriodId { get; set; }
        public Nullable<int> CoverdByTeacherId { get; set; }
        public Nullable<bool> Recovered { get; set; }
    }
}
